### ISSUE TITLE
Add debug mode

### ISSUE THREAD

**Issue by nidhiyedida** [yrahul3910/programmable-resumes#12]
Currently, `progres` will silently fail with no indication of what went wrong. A debug mode is crucial for end-users.

**Comment by yrahul3910** [comment]
Agreed. Marking this p1.

**Comment by yrahul3910** [comment]
This might be something to implement in pysh first. While pysh does print the error if something fails (see example below), we don't know what processes have run (especially in the case where we use `&&` or what their results were.

```
print(str`cat does_not_exist.txt`)
```

**Comment by yrahul3910** [comment]
`pysh` now has this functionality! [eb0cfdb](https://github.com/yrahul3910/pysh/commit/eb0cfdbaf46fdf59c0ae90e7b191f3420f1f43f0) adds the `EXIT_CODE` and `STDERR` variables that we can query :)
